### ISSUE TITLE
Is MvbInvoke always required for Winform controls?

### ISSUE THREAD

**Issue by siquylee** [markjackmilian/MVB#3]
Thank you very much for the great library. I found Mvb after struggling with ReactiveUI framework. I really love Mvb. I think it's the missing component for a perfect Winform framework. I tried several MVVM/MVC frameworks for  Winform but not sastified. I have an issue when applying Mvb for Winform application. When I used MvbInvoke  to handle MvbAction and update control's properties, the form was frozen for several seconds. If I update control directly then the issue did not happen. 

Did I use MvbInvoke wrong in somewhere?

**Comment by markjackmilian** [comment]
Hi, thanks for appreciating my work. That's some strange behavior you describe, do you have any way to share the repository or code snippet?
The only thing the MVCAction does is make sure that the UI change happens on the main thread

**Comment by siquylee** [comment]
Sorry, I was wrong. It's not an issue of MvbInvoke . I could fix the frozen issue. My project is a MS Office add-in with several Winform forms. Thank a lot again!!!
